---
- name: Deploy the MariaDB database
  hosts: db
  become: yes

  tasks:
    - name: Install the MariaDB package
      package:
        name: "{{ mariadb_package }}"
        state: present

    - name: Enable and start the MariaDB database
      service:
        name: "{{ mariadb_service }}"
        state: started
        enabled: yes

