---
- name: test the custom ansible102 module
  hosts: all
  become: yes
  tasks:
    - name: run the new module
      ansible102:
      register: testout
    - name: dump test output
      debug:
        msg: '{{ testout }}'
