- name: Install standard motd
  template:
    src: templates/motd.j2
    dest: /etc/motd

- name: Install firewalld
  package:
    name: firewalld
    state: present

- name: Enable and start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
